#!/bin/bash

restore=$HOME/restore
if ! [[ -d $restore ]]
then
 mkdir $restore
fi
exists=$(ls $HOME | grep -E -o "$HOME/Backup-[0-9]{4}-[0-9]{2}-[0-9]{2}")
if [[ $exists == "" ]]
then
 echo "No backups found"
 exit 1
fi
backup=$(find "$HOME/Backup-"* -maxdepth 0 | sort -n | tail -n 1)
echo $backup
#if [ $backup == "" ]
#then
# echo "No backups found"
# exit 1
#fi
for i in $(ls $backup -1)
do
 if [[ $(echo $i | grep -E -o "[0-9]{4}-[0-9]{2}-[0-9]{2}") == "" ]]
 then
  if [[ $(ls $backup/$i.* 2>/dev/null | grep -E -o "[0-9]{4}-[0-9]{2}-[0-9]{2}") == "" ]]
  then
   cp $backup/$i $restore/$i
  fi
 fi
done
